name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag grammer-server:1.1.0
      - name: Push Docker image with tag
        run: docker push aleksel/grammer-server:1.1.0
        #run: docker tag  aleksel/language-helper-server:${TAG} aleksel/language-helper-server
