name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag grammer-server:$(date +%s)
      - name: Publish Docker
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          # The name of the image you would like to push
          name: grammer-server
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          # Use registry for pushing to a custom registry
          registry: aleksel/grammer-server
